#!/bin/sh

echo 'http://dl-cdn.alpinelinux.org/alpine/v3.4/main
http://dl-cdn.alpinelinux.org/alpine/v3.4/community
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
' > /etc/apk/repositories

apk update
apk add --update "$@" && rm -rf /var/cache/apk/*
apk upgrade
